/*
 * Flutter Blue Plus API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.SchemaAdvertisementData;
import org.openapitools.client.model.SchemaBluetoothDevice;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SchemaScanResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-20T01:41:46.146266-07:00[America/Los_Angeles]")
public class SchemaScanResult {
  public static final String SERIALIZED_NAME_DEVICE = "device";
  @SerializedName(SERIALIZED_NAME_DEVICE)
  private SchemaBluetoothDevice device;

  public static final String SERIALIZED_NAME_ADVERTISEMENT_DATA = "advertisement_data";
  @SerializedName(SERIALIZED_NAME_ADVERTISEMENT_DATA)
  private SchemaAdvertisementData advertisementData;

  public static final String SERIALIZED_NAME_RSSI = "rssi";
  @SerializedName(SERIALIZED_NAME_RSSI)
  private Integer rssi;

  public SchemaScanResult() {
  }

  public SchemaScanResult device(SchemaBluetoothDevice device) {
    
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @javax.annotation.Nonnull

  public SchemaBluetoothDevice getDevice() {
    return device;
  }


  public void setDevice(SchemaBluetoothDevice device) {
    this.device = device;
  }


  public SchemaScanResult advertisementData(SchemaAdvertisementData advertisementData) {
    
    this.advertisementData = advertisementData;
    return this;
  }

   /**
   * Get advertisementData
   * @return advertisementData
  **/
  @javax.annotation.Nonnull

  public SchemaAdvertisementData getAdvertisementData() {
    return advertisementData;
  }


  public void setAdvertisementData(SchemaAdvertisementData advertisementData) {
    this.advertisementData = advertisementData;
  }


  public SchemaScanResult rssi(Integer rssi) {
    
    this.rssi = rssi;
    return this;
  }

   /**
   * Get rssi
   * @return rssi
  **/
  @javax.annotation.Nonnull

  public Integer getRssi() {
    return rssi;
  }


  public void setRssi(Integer rssi) {
    this.rssi = rssi;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemaScanResult schemaScanResult = (SchemaScanResult) o;
    return Objects.equals(this.device, schemaScanResult.device) &&
        Objects.equals(this.advertisementData, schemaScanResult.advertisementData) &&
        Objects.equals(this.rssi, schemaScanResult.rssi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(device, advertisementData, rssi);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemaScanResult {\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    advertisementData: ").append(toIndentedString(advertisementData)).append("\n");
    sb.append("    rssi: ").append(toIndentedString(rssi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("device");
    openapiFields.add("advertisement_data");
    openapiFields.add("rssi");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("device");
    openapiRequiredFields.add("advertisement_data");
    openapiRequiredFields.add("rssi");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SchemaScanResult
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SchemaScanResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SchemaScanResult is not found in the empty JSON string", SchemaScanResult.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SchemaScanResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SchemaScanResult` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SchemaScanResult.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `device`
      SchemaBluetoothDevice.validateJsonObject(jsonObj.getAsJsonObject("device"));
      // validate the required field `advertisement_data`
      SchemaAdvertisementData.validateJsonObject(jsonObj.getAsJsonObject("advertisement_data"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SchemaScanResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SchemaScanResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SchemaScanResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SchemaScanResult.class));

       return (TypeAdapter<T>) new TypeAdapter<SchemaScanResult>() {
           @Override
           public void write(JsonWriter out, SchemaScanResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SchemaScanResult read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SchemaScanResult given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SchemaScanResult
  * @throws IOException if the JSON string is invalid with respect to SchemaScanResult
  */
  public static SchemaScanResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SchemaScanResult.class);
  }

 /**
  * Convert an instance of SchemaScanResult to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

