/*
 * Flutter Blue Plus API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.SchemaBluetoothCharacteristic;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SchemaBluetoothService
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-20T01:41:46.146266-07:00[America/Los_Angeles]")
public class SchemaBluetoothService {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_REMOTE_ID = "remote_id";
  @SerializedName(SERIALIZED_NAME_REMOTE_ID)
  private String remoteId;

  public static final String SERIALIZED_NAME_IS_PRIMARY = "is_primary";
  @SerializedName(SERIALIZED_NAME_IS_PRIMARY)
  private Boolean isPrimary;

  public static final String SERIALIZED_NAME_CHARACTERISTICS = "characteristics";
  @SerializedName(SERIALIZED_NAME_CHARACTERISTICS)
  private List<SchemaBluetoothCharacteristic> characteristics = new ArrayList<>();

  public static final String SERIALIZED_NAME_INCLUDED_SERVICES = "included_services";
  @SerializedName(SERIALIZED_NAME_INCLUDED_SERVICES)
  private List<SchemaBluetoothService> includedServices = new ArrayList<>();

  public SchemaBluetoothService() {
  }

  public SchemaBluetoothService uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @javax.annotation.Nonnull

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public SchemaBluetoothService remoteId(String remoteId) {
    
    this.remoteId = remoteId;
    return this;
  }

   /**
   * Get remoteId
   * @return remoteId
  **/
  @javax.annotation.Nonnull

  public String getRemoteId() {
    return remoteId;
  }


  public void setRemoteId(String remoteId) {
    this.remoteId = remoteId;
  }


  public SchemaBluetoothService isPrimary(Boolean isPrimary) {
    
    this.isPrimary = isPrimary;
    return this;
  }

   /**
   * Get isPrimary
   * @return isPrimary
  **/
  @javax.annotation.Nonnull

  public Boolean getIsPrimary() {
    return isPrimary;
  }


  public void setIsPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
  }


  public SchemaBluetoothService characteristics(List<SchemaBluetoothCharacteristic> characteristics) {
    
    this.characteristics = characteristics;
    return this;
  }

  public SchemaBluetoothService addCharacteristicsItem(SchemaBluetoothCharacteristic characteristicsItem) {
    if (this.characteristics == null) {
      this.characteristics = new ArrayList<>();
    }
    this.characteristics.add(characteristicsItem);
    return this;
  }

   /**
   * Get characteristics
   * @return characteristics
  **/
  @javax.annotation.Nonnull

  public List<SchemaBluetoothCharacteristic> getCharacteristics() {
    return characteristics;
  }


  public void setCharacteristics(List<SchemaBluetoothCharacteristic> characteristics) {
    this.characteristics = characteristics;
  }


  public SchemaBluetoothService includedServices(List<SchemaBluetoothService> includedServices) {
    
    this.includedServices = includedServices;
    return this;
  }

  public SchemaBluetoothService addIncludedServicesItem(SchemaBluetoothService includedServicesItem) {
    if (this.includedServices == null) {
      this.includedServices = new ArrayList<>();
    }
    this.includedServices.add(includedServicesItem);
    return this;
  }

   /**
   * Get includedServices
   * @return includedServices
  **/
  @javax.annotation.Nonnull

  public List<SchemaBluetoothService> getIncludedServices() {
    return includedServices;
  }


  public void setIncludedServices(List<SchemaBluetoothService> includedServices) {
    this.includedServices = includedServices;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemaBluetoothService schemaBluetoothService = (SchemaBluetoothService) o;
    return Objects.equals(this.uuid, schemaBluetoothService.uuid) &&
        Objects.equals(this.remoteId, schemaBluetoothService.remoteId) &&
        Objects.equals(this.isPrimary, schemaBluetoothService.isPrimary) &&
        Objects.equals(this.characteristics, schemaBluetoothService.characteristics) &&
        Objects.equals(this.includedServices, schemaBluetoothService.includedServices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, remoteId, isPrimary, characteristics, includedServices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemaBluetoothService {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    remoteId: ").append(toIndentedString(remoteId)).append("\n");
    sb.append("    isPrimary: ").append(toIndentedString(isPrimary)).append("\n");
    sb.append("    characteristics: ").append(toIndentedString(characteristics)).append("\n");
    sb.append("    includedServices: ").append(toIndentedString(includedServices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("uuid");
    openapiFields.add("remote_id");
    openapiFields.add("is_primary");
    openapiFields.add("characteristics");
    openapiFields.add("included_services");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("uuid");
    openapiRequiredFields.add("remote_id");
    openapiRequiredFields.add("is_primary");
    openapiRequiredFields.add("characteristics");
    openapiRequiredFields.add("included_services");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SchemaBluetoothService
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SchemaBluetoothService.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SchemaBluetoothService is not found in the empty JSON string", SchemaBluetoothService.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SchemaBluetoothService.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SchemaBluetoothService` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SchemaBluetoothService.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid").toString()));
      }
      if (!jsonObj.get("remote_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `remote_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remote_id").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("characteristics").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `characteristics` to be an array in the JSON string but got `%s`", jsonObj.get("characteristics").toString()));
      }

      JsonArray jsonArraycharacteristics = jsonObj.getAsJsonArray("characteristics");
      // validate the required field `characteristics` (array)
      for (int i = 0; i < jsonArraycharacteristics.size(); i++) {
        SchemaBluetoothCharacteristic.validateJsonObject(jsonArraycharacteristics.get(i).getAsJsonObject());
      };
      // ensure the json data is an array
      if (!jsonObj.get("included_services").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `included_services` to be an array in the JSON string but got `%s`", jsonObj.get("included_services").toString()));
      }

      JsonArray jsonArrayincludedServices = jsonObj.getAsJsonArray("included_services");
      // validate the required field `included_services` (array)
      for (int i = 0; i < jsonArrayincludedServices.size(); i++) {
        SchemaBluetoothService.validateJsonObject(jsonArrayincludedServices.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SchemaBluetoothService.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SchemaBluetoothService' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SchemaBluetoothService> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SchemaBluetoothService.class));

       return (TypeAdapter<T>) new TypeAdapter<SchemaBluetoothService>() {
           @Override
           public void write(JsonWriter out, SchemaBluetoothService value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SchemaBluetoothService read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SchemaBluetoothService given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SchemaBluetoothService
  * @throws IOException if the JSON string is invalid with respect to SchemaBluetoothService
  */
  public static SchemaBluetoothService fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SchemaBluetoothService.class);
  }

 /**
  * Convert an instance of SchemaBluetoothService to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

