/*
 * Flutter Blue Plus API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SchemaSetNotificationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-20T01:41:46.146266-07:00[America/Los_Angeles]")
public class SchemaSetNotificationRequest {
  public static final String SERIALIZED_NAME_REMOTE_ID = "remote_id";
  @SerializedName(SERIALIZED_NAME_REMOTE_ID)
  private String remoteId;

  public static final String SERIALIZED_NAME_SERVICE_UUID = "service_uuid";
  @SerializedName(SERIALIZED_NAME_SERVICE_UUID)
  private String serviceUuid;

  public static final String SERIALIZED_NAME_SECONDARY_SERVICE_UUID = "secondary_service_uuid";
  @SerializedName(SERIALIZED_NAME_SECONDARY_SERVICE_UUID)
  private String secondaryServiceUuid;

  public static final String SERIALIZED_NAME_CHARACTERISTIC_UUID = "characteristic_uuid";
  @SerializedName(SERIALIZED_NAME_CHARACTERISTIC_UUID)
  private String characteristicUuid;

  public static final String SERIALIZED_NAME_ENABLE = "enable";
  @SerializedName(SERIALIZED_NAME_ENABLE)
  private Boolean enable;

  public SchemaSetNotificationRequest() {
  }

  public SchemaSetNotificationRequest remoteId(String remoteId) {
    
    this.remoteId = remoteId;
    return this;
  }

   /**
   * Get remoteId
   * @return remoteId
  **/
  @javax.annotation.Nonnull

  public String getRemoteId() {
    return remoteId;
  }


  public void setRemoteId(String remoteId) {
    this.remoteId = remoteId;
  }


  public SchemaSetNotificationRequest serviceUuid(String serviceUuid) {
    
    this.serviceUuid = serviceUuid;
    return this;
  }

   /**
   * Get serviceUuid
   * @return serviceUuid
  **/
  @javax.annotation.Nonnull

  public String getServiceUuid() {
    return serviceUuid;
  }


  public void setServiceUuid(String serviceUuid) {
    this.serviceUuid = serviceUuid;
  }


  public SchemaSetNotificationRequest secondaryServiceUuid(String secondaryServiceUuid) {
    
    this.secondaryServiceUuid = secondaryServiceUuid;
    return this;
  }

   /**
   * Get secondaryServiceUuid
   * @return secondaryServiceUuid
  **/
  @javax.annotation.Nonnull

  public String getSecondaryServiceUuid() {
    return secondaryServiceUuid;
  }


  public void setSecondaryServiceUuid(String secondaryServiceUuid) {
    this.secondaryServiceUuid = secondaryServiceUuid;
  }


  public SchemaSetNotificationRequest characteristicUuid(String characteristicUuid) {
    
    this.characteristicUuid = characteristicUuid;
    return this;
  }

   /**
   * Get characteristicUuid
   * @return characteristicUuid
  **/
  @javax.annotation.Nonnull

  public String getCharacteristicUuid() {
    return characteristicUuid;
  }


  public void setCharacteristicUuid(String characteristicUuid) {
    this.characteristicUuid = characteristicUuid;
  }


  public SchemaSetNotificationRequest enable(Boolean enable) {
    
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @javax.annotation.Nonnull

  public Boolean getEnable() {
    return enable;
  }


  public void setEnable(Boolean enable) {
    this.enable = enable;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemaSetNotificationRequest schemaSetNotificationRequest = (SchemaSetNotificationRequest) o;
    return Objects.equals(this.remoteId, schemaSetNotificationRequest.remoteId) &&
        Objects.equals(this.serviceUuid, schemaSetNotificationRequest.serviceUuid) &&
        Objects.equals(this.secondaryServiceUuid, schemaSetNotificationRequest.secondaryServiceUuid) &&
        Objects.equals(this.characteristicUuid, schemaSetNotificationRequest.characteristicUuid) &&
        Objects.equals(this.enable, schemaSetNotificationRequest.enable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(remoteId, serviceUuid, secondaryServiceUuid, characteristicUuid, enable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemaSetNotificationRequest {\n");
    sb.append("    remoteId: ").append(toIndentedString(remoteId)).append("\n");
    sb.append("    serviceUuid: ").append(toIndentedString(serviceUuid)).append("\n");
    sb.append("    secondaryServiceUuid: ").append(toIndentedString(secondaryServiceUuid)).append("\n");
    sb.append("    characteristicUuid: ").append(toIndentedString(characteristicUuid)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("remote_id");
    openapiFields.add("service_uuid");
    openapiFields.add("secondary_service_uuid");
    openapiFields.add("characteristic_uuid");
    openapiFields.add("enable");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("remote_id");
    openapiRequiredFields.add("service_uuid");
    openapiRequiredFields.add("secondary_service_uuid");
    openapiRequiredFields.add("characteristic_uuid");
    openapiRequiredFields.add("enable");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SchemaSetNotificationRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SchemaSetNotificationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SchemaSetNotificationRequest is not found in the empty JSON string", SchemaSetNotificationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SchemaSetNotificationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SchemaSetNotificationRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SchemaSetNotificationRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("remote_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `remote_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remote_id").toString()));
      }
      if (!jsonObj.get("service_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `service_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("service_uuid").toString()));
      }
      if (!jsonObj.get("secondary_service_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secondary_service_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secondary_service_uuid").toString()));
      }
      if (!jsonObj.get("characteristic_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `characteristic_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("characteristic_uuid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SchemaSetNotificationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SchemaSetNotificationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SchemaSetNotificationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SchemaSetNotificationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SchemaSetNotificationRequest>() {
           @Override
           public void write(JsonWriter out, SchemaSetNotificationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SchemaSetNotificationRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SchemaSetNotificationRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SchemaSetNotificationRequest
  * @throws IOException if the JSON string is invalid with respect to SchemaSetNotificationRequest
  */
  public static SchemaSetNotificationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SchemaSetNotificationRequest.class);
  }

 /**
  * Convert an instance of SchemaSetNotificationRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

