name: vx_flutter_blue_darwin
description: iOS and macOS implementation of the vx_flutter_blue plugin.
version: 7.0.3
homepage: https://github.com/chipweinberger/vx_flutter_blue

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  vx_flutter_blue_platform_interface: 7.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: vx_flutter_blue
    platforms:
      ios:
        pluginClass: FlutterBluePlusPlugin
        dartPluginClass: FlutterBluePlusDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterBluePlusPlugin
        dartPluginClass: FlutterBluePlusDarwin
        sharedDarwinSource: true
