name: vx_flutter_blue_web
description: Web implementation of the vx_flutter_blue plugin.
version: 1.0.0
homepage: https://github.com/vx-daniel/vx_flutter_blue

environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  vx_flutter_blue_platform_interface: 1.0.0
  flutter_web_plugins:
    sdk: flutter
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: vx_flutter_blue
    platforms:
      web:
        pluginClass: VXFlutterBlueWeb
        fileName: vx_flutter_blue_web.dart
