name: vx_flutter_blue_example
description: Demonstrates how to use the vx_flutter_blue plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  vx_flutter_blue:
    # Note: We use a path dependency because the example app & plugin are bundled together.
    # In *your* app you should use ^1.17.3 or similar
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  # Note: We use these dependency overrides to test the example app with the latest changes.
  # In *your* app you should not add these overrides
  vx_flutter_blue_android:
    path: ../../vx_flutter_blue_android
  vx_flutter_blue_darwin:
    path: ../../vx_flutter_blue_darwin
  vx_flutter_blue_linux:
    path: ../../vx_flutter_blue_linux
  vx_flutter_blue_platform_interface:
    path: ../../vx_flutter_blue_platform_interface
  vx_flutter_blue_web:
    path: ../../vx_flutter_blue_web

flutter:
  uses-material-design: true

  # see https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-app-developers
  # disable-swift-package-manager: true
