name: flutter_blue_plus
description: Flutter plugin for connecting and communicating with Bluetooth Low Energy devices.
version: 2.3.0
homepage: https://github.com/chipweinberger/flutter_blue_plus

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

  # Internal release order for publishing to pub.dev:
  # Commands:
  #   0. cd /packages/flutter_blue_plus (if not already there)
  #   1. cd ../flutter_blue_plus_platform_interface && flutter pub publish
  #   2. cd ../flutter_blue_plus_android && flutter pub publish
  #   3. cd ../flutter_blue_plus_darwin && flutter pub publish
  #   4. cd ../flutter_blue_plus_linux && flutter pub publish
  #   5. cd ../flutter_blue_plus_web && flutter pub publish
  #   6. cd ../flutter_blue_plus && flutter pub publish

dependencies:
  flutter:
    sdk: flutter
  # use specific versions to keep all users in sync. 
  #  - users otherwise forget to update all
  #  - simpler bug reporting
  #  - unified changelog
  #  - users can still manually override
  flutter_blue_plus_platform_interface: 9.0.0
  flutter_blue_plus_android: 9.0.0
  flutter_blue_plus_darwin: 9.0.0
  flutter_blue_plus_linux: 9.0.0
  flutter_blue_plus_web: 9.0.0

  # winrt has not been update to 9.0.0 yet.
  # we must temporarily drop support (or fork it..)
  #flutter_blue_plus_winrt: any

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blue_plus_android
      ios:
        default_package: flutter_blue_plus_darwin
      linux:
        default_package: flutter_blue_plus_linux
      macos:
        default_package: flutter_blue_plus_darwin
      web:
        default_package: flutter_blue_plus_web
      windows:
        default_package: flutter_blue_plus_winrt
