name: Help / Question
description: Need help?
title: "[Help]: "
labels: ["help"]
body:
  - type: checkboxes
    attributes:
      label: "Requirements"
      description: 
      options:
        - label: "I've looked at the README 'Common Problems' section"
          required: true
  - type: dropdown
    attributes:
      label: "Have you checked this problem on the example app?"
      description:
      multiple: false
      options:
        - "No"
        - "Yes"
    validations:
      required: true
  - type: input
    id: fbp-version
    attributes:
      label: "FlutterBluePlus Version"
      description: "run `flutter pub deps` in your project"
      placeholder: "ex. 1.31.4"
    validations:
      required: true
  - type: input
    id: flutter-version
    attributes:
      label: "Flutter Version"
      description: "run `flutter --version` in your project"
      placeholder: "ex. 3.10.6"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: "What OS?"
      description: "please add this to your title"
      multiple: true
      options:
        - "Android"
        - "iOS"
        - "macOS"
        - "Web"
        - "All"
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: "OS Version"
      description: "What version of iOS/Android/MacOS/Browser are you on?"
      placeholder: "ex. iOS 17.3.1"
    validations:
      required: true
  - type: input
    id: ble-module
    attributes:
      label: "Bluetooth Module"
      description: "What ble module is your device using?"
      placeholder: "ex. Arduino HC-08, Espressif esp32-s2, TI CC2541, Nordic nRF52840, NXP QN908x"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "What is your problem?"
      placeholder: "What is your problem?"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Paste *ALL* logs!"
      placeholder: "Include logs from the very begining!"
      render: shell
    validations:
      required: true
