name: flutter_blue_plus_macos
description: macOS implementation of the flutter_blue_plus plugin.
version: 1.35.0
homepage: https://github.com/chipweinberger/flutter_blue_plus

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      macos:
        pluginClass: FlutterBluePlusPlugin
        dartPluginClass: FlutterBluePlusMacos
