name: vx_flutter_blue_linux
description: Linux implementation of the vx_flutter_blue plugin.
version: 7.0.3
homepage: https://github.com/chipweinberger/vx_flutter_blue

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  bluez: '>=0.7.8 <0.9.0'
  flutter:
    sdk: flutter
  vx_flutter_blue_platform_interface: 7.0.0
  rxdart: '>=0.27.0 <0.29.0'

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: vx_flutter_blue
    platforms:
      linux:
        dartPluginClass: VXFlutterBlueLinux
