name: core_bluetooth_example
description: Demonstrates how to use the core_bluetooth plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  core_bluetooth:
    # Note: We use a path dependency because the example app & plugin are bundled together.
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # see https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-app-developers
  # disable-swift-package-manager: true
