name: Publish Flutter Blue Plus Darwin
on:
  push:
    tags:
      - 'flutter_blue_plus_darwin-[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/flutter_blue_plus_darwin
